Temperature_data <- read_excel("Desktop/temperature data.xlsx")
View(Temperature_data)
frequency(Temperature_data)
Temperature_data.ts<-ts(Temperature_data,start=c(1989),frequency=1)
class(Temperature_data.ts)
start(Temperature_data.ts)
end(Temperature_data.ts)
frequency(Temperature_data.ts)
summary(Temperature_data.ts)
View(Temperature_data.ts)
plot(Temperature_data.ts)
acf(Temperature_data.ts)
pacf(Temperature_data.ts)
model<-arima(Temperature_data.ts[,2],c(1,2),seasonal = list(order = c(0, 1, 1), period = 12))
predicted<-predict(model, n.ahead=5*1)
predicted
